<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\Task;
use App\Models\TaskUpdate;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Demo users — all share the password "password".
        $admin = User::create([
            'name' => 'Alex Morgan',
            'email' => 'admin@logvera.test',
            'password' => Hash::make('password'),
            'job_title' => 'Product Lead',
            'is_admin' => true,
        ]);

        $members = collect([
            ['name' => 'Priya Sharma', 'email' => 'priya@logvera.test', 'job_title' => 'Backend Engineer'],
            ['name' => 'Diego Ramos', 'email' => 'diego@logvera.test', 'job_title' => 'Frontend Engineer'],
            ['name' => 'Mei Lin', 'email' => 'mei@logvera.test', 'job_title' => 'QA Engineer'],
        ])->map(fn ($u) => User::create([...$u, 'password' => Hash::make('password')]));

        $projects = [
            ['name' => 'Logvera Web App', 'description' => 'Project & daily log management platform.'],
            ['name' => 'Mobile Companion', 'description' => 'React Native companion app.', 'status' => 'active'],
            ['name' => 'Legacy Migration', 'description' => 'Archived migration effort.', 'status' => 'archived'],
        ];

        foreach ($projects as $data) {
            $project = Project::create([
                'name' => $data['name'],
                'description' => $data['description'],
                'owner_id' => $admin->id,
                'status' => $data['status'] ?? 'active',
            ]);

            // Owner + all members belong to the project.
            $project->members()->attach($admin->id, ['role' => 'owner']);
            $members->each(fn ($m) => $project->members()->attach($m->id, ['role' => 'member']));

            $this->seedTasks($project, $admin, $members);
        }
    }

    private function seedTasks(Project $project, User $admin, $members): void
    {
        $types = Task::TYPES;
        $priorities = Task::PRIORITIES;
        $statuses = Task::STATUSES;
        $people = collect([$admin])->merge($members);

        // Spread tasks across recent dates so the timeline has multiple day-groups.
        foreach (range(0, 7) as $i) {
            $date = now()->subDays($i);
            $count = rand(1, 3);

            for ($t = 0; $t < $count; $t++) {
                $status = $statuses[array_rand($statuses)];
                $progress = $status === 'completed' ? 100 : ($status === 'not_started' ? 0 : rand(10, 90));
                $assignee = $people->random();

                $task = $project->tasks()->create([
                    'title' => $this->title(),
                    'description' => 'Sample task generated by the seeder.',
                    'type' => $types[array_rand($types)],
                    'priority' => $priorities[array_rand($priorities)],
                    'status' => $status,
                    'progress' => $progress,
                    'target_date' => $date->toDateString(),
                    'target_time' => sprintf('%02d:00:00', rand(9, 17)),
                    'assigned_user_id' => $assignee->id,
                    'created_by' => $admin->id,
                ]);

                // A couple of update logs per task.
                foreach (range(1, rand(1, 3)) as $u) {
                    TaskUpdate::create([
                        'task_id' => $task->id,
                        'user_id' => $assignee->id,
                        'description' => 'Progress update #'.$u.' — work continuing.',
                        'progress_after' => min(100, $progress),
                        'status_after' => $status,
                    ]);
                }
            }
        }
    }

    private function title(): string
    {
        $items = [
            'Login Page', 'API Integration', 'Database Design', 'Dashboard Charts',
            'File Upload Flow', 'Timeline View', 'Auth Middleware', 'Member Permissions',
            'Task Detail Tabs', 'Search Endpoint', 'Notification Center', 'Responsive Layout',
        ];

        return $items[array_rand($items)];
    }
}
